uoa-ypec413/metacodenition

src/context/AssignmentContext.tsx
src/hooks/useQuestion.tsx
src/pages/AssignmentPage/AssignmentPage.tsx

Closes #63
Questions are now tracked through the user's assignment document. Fixes a number of small issues, as detailed in #63.
Locally.

🔭 Adjust question tracking

---

src/components/NavBar/NavBar.tsx
src/components/SubmissionModal/SubmissionModal.tsx
src/components/SubmissionModal/index.tsx

Adds a modal for confirming a submission - let's the user know that once they submit they cannot go back and edit their answer.
Closes #67 
Locally

✅ Add submission modal

---

src/components/AssignmentFeedbackForm/AssignmentFeedbackForm.tsx
src/components/CodeCopyBox/CodeCopyBox.tsx
src/pages/AssignmentSubmit/AssignmentSubmit.tsx
src/pages/ProblemPage/ProblemPage.tsx

Made components on the assignment submission page smaller and centered them.
Locally

💅 Assignment submission style changes

---

src/components/TestCaseSolver/TestCaseSolver.tsx

Currently, the current/initial test case on the Problem Page is only set on 2 conditions:
1. The test cases have a length greater than 0
2. The current test case is undefined
The second condition ensures that the current test case is only set once. This means that on subsequent questions the current test case is not changed. Only a page refresh will result in the correct test case being displayed.
To fix this bug, I've removed this condition.
Fixes #70 
Locally via dev tools console

:bug: Fix initial test case

---

src/components/ChangeAssignmentButton/ChangeAssignmentButton.tsx
src/components/CodeRunArea/CodeRunArea.tsx
src/components/CodeRunArea/InputArea.tsx
src/components/LogOutButton/LogOutButton.tsx
src/components/NavBar/NavBar.tsx
src/components/TestCaseSolver/TestCaseSolver.tsx
src/pages/DesignPage/DesignPage.tsx
src/pages/EvaluationPage/EvaluationPage.tsx
src/pages/TestCasePage/TestCasePage.tsx

Adds changes to do with improving user feedback on various actions. These include:
- Adds tooltips to refresh, shuffle, edit assignment, log out, and submit buttons.
- Fixes the Run button's loading state
- Adds a notification when no test cases are selected in the run test cases page
- Fixes the Problem Page question skipping issue
- Adds a tick for 300ms when a highlight is submitted
- Adds a tick for 300ms when parsons problems are submitted
Closes #73 
Locally

:speech_balloon: User feedback improvements

---

src/components/MainLinks/MainLink.tsx
src/components/NavBar/NavBar.tsx
src/components/NavigationModal/NavigationModal.tsx
src/components/NavigationModal/index.tsx
src/components/TestCaseSolver/TestCaseSolver.tsx
src/context/AssignmentContext.tsx
src/hooks/useParsons.tsx
src/pages/DesignPage/DesignPage.tsx
src/pages/EvaluationPage/EvaluationPage.tsx
src/pages/TestCasePage/TestCasePage.tsx

Closes #74 and #77 
Unsaved changes are now tracked, and users will be prompted when attempting to navigate away from a page or question with unsaved changes.
I also fixed the issue with user-generated test cases not deleting properly.
Locally

📔 Track Save State

---

.eslintrc.json
src/App.tsx
src/components/ChangeAssignmentButton/ChangeAssignmentButton.tsx
src/components/CodeEditor/CodeEditor.tsx
src/components/CodeRunArea/CodeRunArea.tsx
src/components/FirebaseAnalytics/FirebaseAnalytics.tsx
src/components/FirebaseAnalytics/index.tsx
src/components/NavBar/NavBar.tsx
src/components/PreSurveyForm/PreSurveyForm.tsx
src/components/PreSurveyForm/index.tsx
src/components/ProblemPopover/ProblemPopover.tsx
src/components/SubmissionModal/SubmissionModal.tsx
src/components/TestCaseSolver/TestCaseSolver.tsx
src/hooks/useUser.tsx
src/pages/AssignmentPage/index.tsx
src/pages/AssignmentSubmit/AssignmentSubmit.tsx
src/pages/DesignPage/DesignPage.tsx
src/pages/EntryPage/EntryPage.tsx
src/pages/EntryPage/index.tsx
src/pages/EvaluationPage/EvaluationPage.tsx
src/pages/HomePage/HomePage.tsx
src/pages/TestCasePage/TestCasePage.tsx
src/util/firebase/index.ts

Adds google analytics to our project.
Closes #47 
Adds a pre-survey to collect user info and add to Analytics user properties 
- Gender, Ethnicity, Previous Programming Experience (0-5)
Includes logging the following events:
- page_view
- auto_generate_comments
- run_code
- submit_question
- open_problem_popover
- submit_question
- confirm_submit_question
- check_test_case
- parameters: 
- current_test_case: the test case input being checked
- correct: if the answer was correct
- shuffle_test_cases
- parameters:
- current_test_case
- next_test_case
- parameters:
- current_test_case
- reset_test_cases
- highlight
- save_action
- delete_action
- save_parsons
- rearrange_parsons
- run_test_cases
- parameters:
- num_test_cases: the number of test cases being run
- num_passed: the number of …

📈 Add analytics

---

src/components/CodeRunArea/CodeRunArea.tsx

The code run area used the old notification style (not the global notifications context + component) which was inconsistent style-wise and would pop under the page's header.
I have changed the code for this component to be in line with the rest of the codebase.
Tested locally

🔨 Fix Notification Glitch

---

src/components/InterventionModal/InterventionModal.tsx
src/components/SettingsDrawer/SettingsDrawer.tsx
src/util/firebase/authentication.ts

Adds analytics event logging for selecting interventions.
Closes #84 
Locally via Firebase Analytics DebugView

📊 Add select interventions analytics event

---

src/components/NavBar/NavBar.tsx
src/components/ProblemPopover/ProblemPopover.tsx
src/components/ProblemText/ProblemText.tsx
src/components/ProblemText/index.tsx
src/hooks/useQuestion.tsx
src/index.css
src/pages/DesignPage/DesignPage.tsx
src/pages/EvaluationPage/EvaluationPage.tsx
src/pages/ProblemPage/ProblemPage.tsx

* Tooltips now follow the mouse around
* Squashed a bug with parsons problems on small screens
* Stop the user from submitting when they aren't on the last active intervention
Closes #88 
Locally

📆 Get things ready for demo

---

src/components/CodeRunArea/TestCaseInput.tsx
src/components/TestCaseSolver/TestCaseSolver.tsx
src/hooks/useParsons.tsx
src/hooks/useQuestion.tsx
src/hooks/useTestCases.tsx
src/pages/EvaluationPage/AddActionButton.tsx
src/pages/EvaluationPage/EditFragmentCard.tsx
src/pages/EvaluationPage/EvaluationPage.tsx
src/pages/EvaluationPage/FragmentCard.tsx
src/pages/EvaluationPage/NewFragmentCard.tsx
src/pages/TestCasePage/TestCasePage.tsx
src/util/testcase-helpers.ts

I've changed the "evaluate a solution" page to fit the design proposed by @uoa-ypec413 
Closes #95
BEFORE MERGING:
Locally

🎬 Implement new design for evaluating a solution

---

src/components/BottomPanel/BottomPanel.tsx
src/components/CodeRunArea/OutputArea.tsx
src/pages/EntryPage/EntryPage.tsx
src/util/testcase-helpers.ts

* Fixes wording of user-generated test cases that require arrays
* Adds the ability to scroll in the bottom half of implementation page.
* Adds a video to the entry page
* Adds contact info to the entry page
Locally

🌠 Make final tweaks before releasing for lab

---

src/components/CodeEditor/CodeEditor.tsx
src/components/CodeRunArea/CodeRunArea.tsx
src/components/FirebaseAnalytics/FirebaseAnalytics.tsx
src/components/InterventionModal/InterventionModal.tsx
src/components/NavBar/NavBar.tsx
src/components/SettingsDrawer/SettingsDrawer.tsx
src/components/SubmissionModal/SubmissionModal.tsx
src/components/TestCaseSolver/TestCaseSolver.tsx
src/hooks/useUser.tsx
src/pages/DesignPage/DesignPage.tsx
src/pages/EvaluationPage/EvaluationPage.tsx
src/pages/ProblemPage/ProblemPage.tsx
src/pages/TestCasePage/TestCasePage.tsx

Added question number logging to all GA events.
Added extra code to ensure that UPI and user group are logged.
Tested using debug view, idk how effective this actually will be but its definitely better than what we had before.

🌔 Analytics enhancements

---

src/components/TestCaseSolver/TestCaseSolver.tsx
src/pages/DesignPage/DesignPage.tsx

* Added question number in one place where it was missing
* Changed test case input to test case id reporting (as input is now an object). Test case Ids are garuanteed to be much smaller than 100 characters.

🕸️ Small analytics fixes

---

src/components/TestCaseSolver/TestCaseSolver.tsx

Make button red so people are less likely to click accidentally 😨 
It hasn't

:red_circle: Make reset test cases button red

---

src/pages/ApplicationShell/ApplicationShell.tsx

Move user property reporting within `ApplicationShell.tsx` to try and ensure that it is always captured.
Tested locally with debugview. Deleted GA cookies, and the correct user properties were re-reported.

📋 Report user properties within ApplicationShell.tsx

---

src/components/CodeEditor/CodeEditor.tsx
src/components/CodeRunArea/CodeRunArea.tsx
src/components/FirebaseAnalytics/FirebaseAnalytics.tsx
src/components/InterventionModal/InterventionModal.tsx
src/components/NavBar/NavBar.tsx
src/components/SettingsDrawer/SettingsDrawer.tsx
src/components/SubmissionModal/SubmissionModal.tsx
src/components/TestCaseSolver/TestCaseSolver.tsx
src/hooks/useUser.tsx
src/pages/DesignPage/DesignPage.tsx
src/pages/EvaluationPage/EvaluationPage.tsx
src/pages/ProblemPage/ProblemPage.tsx
src/pages/TestCasePage/TestCasePage.tsx

🦆 🦆 🦆 
we will see if this solves our issues
* Added `user_upi` and `user_testing_group` fields to GA events.

🦆 Add user_upi and user_testing_group fields to GA

---

src/components/CodeRunArea/OutputArea.tsx

Fixes a bug where large outputs are too wide for the screen and not visible.
#108 
Locally
iPad mini with wrapping visible:

:fire: Fix hidden output in implementation page

---

src/hooks/useTestCases.tsx

HOTFIX
Ignore trailing whitespace on stdout and the expected value of stdout so that students don't have to worry about newline characters etc.
This brings our behavior into line with coderunner.
Not tested yet, will test on deploy

🧯 Ignore trailing whitespace

---

.eslintrc.json
package-lock.json
package.json
src/components/AppNotifications/AppNotifications.tsx
src/hooks/useTestCases.tsx

Fixing the addition of test cases. Currently broken due to an optional field being persisted to Firestore.
Locally

🔧 Fix adding test cases 

---

src/components/AppNotifications/AppNotifications.tsx
src/components/SubmissionModal/SubmissionModal.tsx
src/components/TestCaseSolver/TestCaseSolver.tsx
src/components/generics/GenericInput/GenericInput.tsx
src/hooks/useTestCases.tsx
src/pages/ApplicationShell/ApplicationShell.tsx
src/pages/TestCasePage/TestCasePage.tsx

From the discord:
>I must say it has certian elements that remove from the overall polish
Like the notification u get in the top left that ur code passed or failed
The blur on the bg for it imo is bad
I have:
* Removed blur from notifications
* Prevented test-cases from re-arranging themselves while being ran
* Fixed the behavior of the parent check box in the test case page, and added indeterminate state
* Added the ability to move through test cases with the enter key on the problem page
Locally

💅 Add overall polish
